// flow-typed signature: e87909473fb52ed65293784b8e06c375
// flow-typed version: <<STUB>>/electron_v2.0.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron/cli' {
  declare module.exports: any;
}

declare module 'electron/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron/cli.js' {
  declare module.exports: $Exports<'electron/cli'>;
}
declare module 'electron/index' {
  declare module.exports: $Exports<'electron'>;
}
declare module 'electron/index.js' {
  declare module.exports: $Exports<'electron'>;
}
declare module 'electron/install.js' {
  declare module.exports: $Exports<'electron/install'>;
}
