// flow-typed signature: 8faa6f4b025f65be052e3b65f1138fcf
// flow-typed version: <<STUB>>/esdoc-importpath-plugin_v1.0.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-importpath-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-importpath-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-importpath-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-importpath-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-importpath-plugin/src/Plugin'>;
}
