// flow-typed signature: 582533dbbd6ce55b261f1cd64d521383
// flow-typed version: <<STUB>>/s3-deploy_v1.1.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's3-deploy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's3-deploy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's3-deploy/dist/cloudfront' {
  declare module.exports: any;
}

declare module 's3-deploy/dist/deploy' {
  declare module.exports: any;
}

declare module 's3-deploy/dist/index' {
  declare module.exports: any;
}

declare module 's3-deploy/dist/MSG' {
  declare module.exports: any;
}

declare module 's3-deploy/dist/utils' {
  declare module.exports: any;
}

declare module 's3-deploy/src/cloudfront' {
  declare module.exports: any;
}

declare module 's3-deploy/src/deploy' {
  declare module.exports: any;
}

declare module 's3-deploy/src/index' {
  declare module.exports: any;
}

declare module 's3-deploy/src/MSG' {
  declare module.exports: any;
}

declare module 's3-deploy/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 's3-deploy/dist/cloudfront.js' {
  declare module.exports: $Exports<'s3-deploy/dist/cloudfront'>;
}
declare module 's3-deploy/dist/deploy.js' {
  declare module.exports: $Exports<'s3-deploy/dist/deploy'>;
}
declare module 's3-deploy/dist/index.js' {
  declare module.exports: $Exports<'s3-deploy/dist/index'>;
}
declare module 's3-deploy/dist/MSG.js' {
  declare module.exports: $Exports<'s3-deploy/dist/MSG'>;
}
declare module 's3-deploy/dist/utils.js' {
  declare module.exports: $Exports<'s3-deploy/dist/utils'>;
}
declare module 's3-deploy/src/cloudfront.js' {
  declare module.exports: $Exports<'s3-deploy/src/cloudfront'>;
}
declare module 's3-deploy/src/deploy.js' {
  declare module.exports: $Exports<'s3-deploy/src/deploy'>;
}
declare module 's3-deploy/src/index.js' {
  declare module.exports: $Exports<'s3-deploy/src/index'>;
}
declare module 's3-deploy/src/MSG.js' {
  declare module.exports: $Exports<'s3-deploy/src/MSG'>;
}
declare module 's3-deploy/src/utils.js' {
  declare module.exports: $Exports<'s3-deploy/src/utils'>;
}
