// flow-typed signature: 9bf46e632ce80e26c5b2ed8290509ef0
// flow-typed version: <<STUB>>/webpack-build-notifier_v0.1.28/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-build-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-build-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-build-notifier/index' {
  declare module.exports: $Exports<'webpack-build-notifier'>;
}
declare module 'webpack-build-notifier/index.js' {
  declare module.exports: $Exports<'webpack-build-notifier'>;
}
